const DATA_URLS=['https://ptaorg.github.io/PTAorg/data/boe-map.json','https://ptaorg.github.io/PTAorg/data/boe-map-rest.json'];
let allRecords=[],filtered=[],activePref='',map=null,mapLayer=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unique=a=>[...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'ja'));
const prefCoords={北海道:[43.064,141.347],青森県:[40.824,140.740],岩手県:[39.703,141.153],宮城県:[38.268,140.872],秋田県:[39.718,140.103],山形県:[38.240,140.363],福島県:[37.750,140.467],茨城県:[36.341,140.446],栃木県:[36.566,139.884],群馬県:[36.391,139.061],埼玉県:[35.857,139.649],千葉県:[35.605,140.123],東京都:[35.690,139.692],神奈川県:[35.448,139.643],新潟県:[37.902,139.023],富山県:[36.695,137.211],石川県:[36.594,136.626],福井県:[36.065,136.222],山梨県:[35.664,138.568],長野県:[36.651,138.181],岐阜県:[35.391,136.722],静岡県:[34.977,138.383],愛知県:[35.180,136.907],三重県:[34.730,136.509],滋賀県:[35.004,135.868],京都府:[35.021,135.756],大阪府:[34.686,135.520],兵庫県:[34.691,135.183],奈良県:[34.685,135.833],和歌山県:[34.226,135.168],鳥取県:[35.503,134.238],島根県:[35.472,133.051],岡山県:[34.661,133.935],広島県:[34.397,132.459],山口県:[34.186,131.471],徳島県:[34.066,134.559],香川県:[34.340,134.043],愛媛県:[33.842,132.766],高知県:[33.559,133.531],福岡県:[33.607,130.418],佐賀県:[33.249,130.299],長崎県:[32.745,129.874],熊本県:[32.790,130.742],大分県:[33.238,131.613],宮崎県:[31.911,131.424],鹿児島県:[31.560,130.558],沖縄県:[26.212,127.681]};
function calcRisk(records){let score=0;let counts={fee:0,privacy:0,staff:0,join:0};records.forEach(r=>{const t=[r.category,r.summary,(r.tags||[]).join(' ')].join(' ');if(/会費|徴収|学校徴収金|委任|代理/.test(t)){score+=3;counts.fee++}if(/個人情報|名簿|同意|目的外/.test(t)){score+=3;counts.privacy++}if(/教職員|職専免|職務|校務|公務|勤務時間/.test(t)){score+=2;counts.staff++}if(/入会|意思|みなし|申込|任意/.test(t)){score+=2;counts.join++}});return{score,counts};}
function scoreColor(score){if(score>=24)return'#b91c1c';if(score>=14)return'#dc2626';if(score>=8)return'#f97316';if(score>=3)return'#eab308';return'#94a3b8';}
function riskLabel(score){if(score>=24)return'高リスク';if(score>=14)return'要監視';if(score>=8)return'注意';if(score>=3)return'論点あり';return'低';}
function mainIssue(counts){const arr=[['会費徴収',counts.fee],['個人情報',counts.privacy],['教職員関与',counts.staff],['入会・意思確認',counts.join]].sort((a,b)=>b[1]-a[1]);return arr[0][1]?arr[0][0]:'その他';}
function renderMap(){if(!window.L||!$('pta-map'))return;if(!map){map=L.map('pta-map').setView([37.5,137.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);mapLayer=L.layerGroup().addTo(map);}mapLayer.clearLayers();const prefs=unique(allRecords.map(r=>r.prefecture));prefs.forEach(pref=>{const c=prefCoords[pref];if(!c)return;const rs=allRecords.filter(r=>r.prefecture===pref);const risk=calcRisk(rs);const color=scoreColor(risk.score);const radius=Math.min(34,7+Math.sqrt(risk.score)*5);const marker=L.circleMarker(c,{radius,color,fillColor:color,fillOpacity:.62,weight:2}).addTo(mapLayer);const topTags=unique(rs.flatMap(r=>r.tags||[])).slice(0,8).map(t=>`<span style="display:inline-block;margin:2px;padding:2px 6px;border-radius:999px;background:#f1f5f9">${esc(t)}</span>`).join('');marker.bindPopup(`<b>${esc(pref)}</b><br>件数：${rs.length}<br>危険度：${risk.score}（${riskLabel(risk.score)}）<br>主論点：${esc(mainIssue(risk.counts))}<br>${topTags}<br><button onclick="selectPrefFromMap('${esc(pref)}')">この都道府県で絞り込む</button>`);marker.on('click',()=>selectPrefFromMap(pref));});setTimeout(()=>map.invalidateSize(),100);}
window.selectPrefFromMap=function(pref){activePref=pref;$('boe-pref').value=pref;applyFilters();document.getElementById('boe-list')?.scrollIntoView({behavior:'smooth',block:'start'});}
function renderCounters(){const p=unique(allRecords.map(r=>r.prefecture));const m=unique(allRecords.map(r=>r.municipality));const t=unique(allRecords.flatMap(r=>r.tags||[]));$('boe-counters').innerHTML=`<div class="boe-counter"><b>${allRecords.length}</b><span>登録回答</span></div><div class="boe-counter"><b>${p.length}</b><span>都道府県</span></div><div class="boe-counter"><b>${m.length}</b><span>自治体</span></div><div class="boe-counter"><b>${t.length}</b><span>タグ</span></div>`}
function renderFilters(){unique(allRecords.flatMap(r=>r.tags||[])).forEach(t=>$('boe-tag').insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));unique(allRecords.map(r=>r.prefecture)).forEach(p=>$('boe-pref').insertAdjacentHTML('beforeend',`<option>${esc(p)}</option>`))}
function renderPrefs(){const prefs=unique(allRecords.map(r=>r.prefecture));$('boe-prefgrid').innerHTML=prefs.map(p=>`<button class="boe-pref ${activePref===p?'active':''}" data-pref="${esc(p)}"><b>${esc(p)}</b><small>${allRecords.filter(r=>r.prefecture===p).length}件</small></button>`).join('');document.querySelectorAll('.boe-pref').forEach(b=>b.onclick=()=>{activePref=activePref===b.dataset.pref?'':b.dataset.pref;$('boe-pref').value=activePref;applyFilters()})}
function card(r){return`<article class="boe-card"><span class="boe-cat">${esc(r.category)}</span><h3>${esc(r.prefecture)} ${esc(r.municipality)}</h3><p class="boe-meta">${esc(r.date)} ／ ${esc(r.source_type)} ／ ${esc(r.status)}</p><p>${esc(r.summary)}</p><div class="boe-tags">${(r.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="boe-detail" data-id="${esc(r.id)}">詳細表示</button></article>`}
function renderRecords(){$('boe-list').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="boe-empty">該当する回答はありません。</div>';document.querySelectorAll('.boe-detail').forEach(b=>b.onclick=()=>showDetail(allRecords.find(r=>r.id===b.dataset.id)))}
function showDetail(r){if(!r)return;$('boe-detail-title').textContent=`${r.prefecture} ${r.municipality}`;$('boe-detail-meta').textContent=`${r.date} ／ ${r.category}`;$('boe-detail-body').className='';$('boe-detail-body').innerHTML=`<p>${esc(r.summary)}</p><div class="boe-tags">${(r.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div>`}
function render(){renderCounters();renderPrefs();renderRecords();renderMap();if(filtered[0])showDetail(filtered[0])}
function applyFilters(){const term=$('boe-q').value.trim().toLowerCase();const tag=$('boe-tag').value;const pref=$('boe-pref').value||activePref;filtered=allRecords.filter(r=>{const hay=[r.prefecture,r.municipality,r.category,r.summary,(r.tags||[]).join(' ')].join(' ').toLowerCase();return(!term||hay.includes(term))&&(!tag||(r.tags||[]).includes(tag))&&(!pref||r.prefecture===pref)});render()}
function applyInitialParams(){const params=new URLSearchParams(location.search);const q=params.get('q')||params.get('issue')||'';const pref=params.get('pref')||'';if(q&&$('boe-q'))$('boe-q').value=q;if(pref&&$('boe-pref')){activePref=pref;$('boe-pref').value=pref;}if(q||pref)applyFilters();}
Promise.all(DATA_URLS.map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u);return r.json()}))).then(parts=>{allRecords=parts.flat().sort((a,b)=>a.id.localeCompare(b.id));filtered=allRecords;renderFilters();render();applyInitialParams()}).catch(e=>{$('boe-list').innerHTML='<div class="boe-empty">データを読み込めませんでした。</div>';console.error(e)});
$('boe-q').oninput=applyFilters;$('boe-tag').onchange=applyFilters;$('boe-pref').onchange=()=>{activePref=$('boe-pref').value;applyFilters()};$('boe-reset').onclick=()=>{$('boe-q').value='';$('boe-tag').value='';$('boe-pref').value='';activePref='';filtered=allRecords;render();history.replaceState(null,'',location.pathname)};