const DATA_URLS=['https://ptaorg.github.io/PTAorg/data/boe-map.json','https://ptaorg.github.io/PTAorg/data/boe-map-rest.json'];
let allRecords=[],filtered=[],activePref='';
const $=id=>document.getElementById(id);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unique=a=>[...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),'ja'));
function renderCounters(){const p=unique(allRecords.map(r=>r.prefecture));const m=unique(allRecords.map(r=>r.municipality));const t=unique(allRecords.flatMap(r=>r.tags||[]));$('boe-counters').innerHTML=`<div class="boe-counter"><b>${allRecords.length}</b><span>登録回答</span></div><div class="boe-counter"><b>${p.length}</b><span>都道府県</span></div><div class="boe-counter"><b>${m.length}</b><span>自治体</span></div><div class="boe-counter"><b>${t.length}</b><span>タグ</span></div>`}
function renderFilters(){unique(allRecords.flatMap(r=>r.tags||[])).forEach(t=>$('boe-tag').insertAdjacentHTML('beforeend',`<option>${esc(t)}</option>`));unique(allRecords.map(r=>r.prefecture)).forEach(p=>$('boe-pref').insertAdjacentHTML('beforeend',`<option>${esc(p)}</option>`))}
function renderPrefs(){const prefs=unique(allRecords.map(r=>r.prefecture));$('boe-prefgrid').innerHTML=prefs.map(p=>`<button class="boe-pref ${activePref===p?'active':''}" data-pref="${esc(p)}"><b>${esc(p)}</b><small>${allRecords.filter(r=>r.prefecture===p).length}件</small></button>`).join('');document.querySelectorAll('.boe-pref').forEach(b=>b.onclick=()=>{activePref=activePref===b.dataset.pref?'':b.dataset.pref;$('boe-pref').value=activePref;applyFilters()})}
function card(r){return`<article class="boe-card"><span class="boe-cat">${esc(r.category)}</span><h3>${esc(r.prefecture)} ${esc(r.municipality)}</h3><p class="boe-meta">${esc(r.date)} ／ ${esc(r.source_type)} ／ ${esc(r.status)}</p><p>${esc(r.summary)}</p><div class="boe-tags">${(r.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="boe-detail" data-id="${esc(r.id)}">詳細表示</button></article>`}
function renderRecords(){$('boe-list').innerHTML=filtered.length?filtered.map(card).join(''):'<div class="boe-empty">該当する回答はありません。</div>';document.querySelectorAll('.boe-detail').forEach(b=>b.onclick=()=>showDetail(allRecords.find(r=>r.id===b.dataset.id)))}
function showDetail(r){if(!r)return;$('boe-detail-title').textContent=`${r.prefecture} ${r.municipality}`;$('boe-detail-meta').textContent=`${r.date} ／ ${r.category}`;$('boe-detail-body').className='';$('boe-detail-body').innerHTML=`<p>${esc(r.summary)}</p><div class="boe-tags">${(r.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('')}</div>`}
function render(){renderCounters();renderPrefs();renderRecords();if(filtered[0])showDetail(filtered[0])}
function applyFilters(){const term=$('boe-q').value.trim().toLowerCase();const tag=$('boe-tag').value;const pref=$('boe-pref').value||activePref;filtered=allRecords.filter(r=>{const hay=[r.prefecture,r.municipality,r.category,r.summary,(r.tags||[]).join(' ')].join(' ').toLowerCase();return(!term||hay.includes(term))&&(!tag||(r.tags||[]).includes(tag))&&(!pref||r.prefecture===pref)});render()}
Promise.all(DATA_URLS.map(u=>fetch(u).then(r=>{if(!r.ok)throw new Error(u);return r.json()}))).then(parts=>{allRecords=parts.flat().sort((a,b)=>a.id.localeCompare(b.id));filtered=allRecords;renderFilters();render()}).catch(e=>{$('boe-list').innerHTML='<div class="boe-empty">データを読み込めませんでした。</div>';console.error(e)});
$('boe-q').oninput=applyFilters;$('boe-tag').onchange=applyFilters;$('boe-pref').onchange=()=>{activePref=$('boe-pref').value;applyFilters()};$('boe-reset').onclick=()=>{$('boe-q').value='';$('boe-tag').value='';$('boe-pref').value='';activePref='';filtered=allRecords;render()};